### PR TITLE
A working build is on mysql-pure

### PR DESCRIPTION
**Pull request by jappeace**
see announcement: https://jappie.me/announcing-mysql-pure-fork.html
source: https://github.com/jappeace/mysql-pure
hackage: https://hackage.haskell.org/package/mysql-pure

### CODE REVIEW

**Comment by winterland1989** [comment]
Oh thanks!  I see people asking for new package name issue, but i think should let you decide to use your new repo(and new hackage name) or continue with this one(creating new one is completely OK to me).  if you decide to use this old repo I can add you as developer(and give off the hackage name).

**Comment by jappeace** [comment]
@winterland1989 yes it's all bounds issues.

yeah, giving me access to hacakge and this repo would be the best outcome for me,
however keep in mind that I did merge several packages together like I said in the announcement,
are you okay with that?

Because I intend to keep on doing it like that for convenience.

**Comment by jappeace** [comment]
awesome! thank you, I shall depracate mysql-pure and point it to mysql-haskell and upload a new version tonight :grin: .

**Comment by jappeace** [comment]
@winterland1989 please also follow these steps for automated version bound bumping script to work: For automatic bound bumping: In “Settings” → “Actions” → “General” → “Workflow permissions” tick “Allow GitHub Actions to create and approve pull requests”

**Comment by winterland1989** [comment]
> @winterland1989 please also follow these steps for automated version bound bumping script to work: For automatic bound bumping: In “Settings” → “Actions” → “General” → “Workflow permissions” tick “Allow GitHub Actions to create and approve pull requests”

It's already checked(by you)?

**Comment by jappeace** [comment]
I've not the capability to do so, but it may have been enabled by default due to being an older repo.

**Pull request closed without merging**
