### PR TITLE
Experiment: Use vector for data where length is known

### PR DESCRIPTION
**Pull request by alexbiehl**
For the rows the length is known. Maybe we can get a bit of performance if we use vectors instead of lists here.

### CODE REVIEW

**Comment by winterland1989** [comment]
Did you run the benchmark already? I'd really like to see benchmark result : )

A side note: since groundhog and persistent both use list to do record conversion, we may want to keep `query/query_/queryStmt` as it is, but adding `queryV/queryV_/queryStmtV_`.

**Comment by alexbiehl** [comment]
No I didn't. I am currently on a machine where I can't run MySQL. Maybe you
could run them?

winterland <notifications@github.com> schrieb am Di., 16. Aug. 2016 um
10:00 Uhr:

**Comment by winterland1989** [comment]
OK, i'll give it a shot when i get time.

**Comment by alexbiehl** [comment]
Thanks!

winterland <notifications@github.com> schrieb am Di., 16. Aug. 2016 um
10:06 Uhr:

**Comment by winterland1989** [comment]
I have push a vector based text-protocol along with benchmarks to `vectorRow` branch, but from the benchmark, it seems there's no obvious speedup, here's my result:

```
=============== start benchmark haskell client =============
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m0.616s
user	0m0.790s
sys	0m0.211s
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m0.809s
user	0m1.520s
sys	0m0.239s
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m1.081s
user	0m2.427s
sys	0m0.261s
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m1.379s
user	0m3.320s
sys	0m0.267s
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m3.531s
user	0m8.332s
sys	0m0.693s
=============== benchmark haskell client end ================
=============== start benchmark haskell client (vector) =============
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m0.648s
user	0m0.828s
sys	0m0.237s
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m0.791s
user	0m1.447s
sys	0m0.218s
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m1.106s
user	0m2.433s
sys	0m0.264s
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m1.390s
user	0m3.317s
sys	0m0.271s
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024
field name: emp_no, birth_date, first_name, last_name, gender, hire_date, 
numbers of rows: 300024

real	0m3.581s
user	0m8.415s
sys	0m0.697s
```

I'll try to use some unsafe tricks like [this one](https://github.com/kawu/vector-binary/blob/master/Data/Vector/Binary.hs#L55) to see if this really works.

**Comment by winterland1989** [comment]
Since vector doesn't provide any speed advantage here, I'll consider to acept a PR which add new method like `queryV/queryV_/queryStmtV_` instead of replacing original list version, is it OK to closing the PR now? @alexbiehl

**Comment by alexbiehl** [comment]
@winterland1989 Yes, please go ahead.

**Comment by winterland1989** [comment]
@alexbiehl  FYI, I have add vector version in vector branch in @9aca187,  thank you for your code, the vector version is as fast as the list one, but for someone who want O(1) indexing, so it will be provided after next release.

**Pull request closed without merging**
